;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Thu Mar 6 2025
; Processor: 8086
; Compiler:  MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================

;====================================================================
; Main.asm file for 8086 (MASM)
;====================================================================
.MODEL SMALL
 
.CODE
START:
    
    MOV AX, 0000H
    MOV DS, AX
    MOV AX, 2324H
    MOV BX, 0010H
LP:   
    MOV [BX], AX
    INC BX
    JMP LP
     
END START
